<section id="biography" class="full-width">
	<p>Apparu pour la première fois au coeur du Var, curieux insatiable, je suis en constante
	recherche de nouveauté et de perfectionnement. Epris de sciences, qu’elles
	soient physiques, linguistiques ou politiques, mais aussi en phase avec le
	monde moderne, j'aime prendre le temps de comprendre ce qui m'entoure,
	ainsi qu'à m'améliorer !</p>
	
	<h2>Mes projets</h2>
	
	<img id="earth-drawing" src="../css/world.png" class="right" />
	
	<p>Je souhaite entrer de plein pied dans la société. Il est pour moi
	essentiel de maintenir une activité aussi pérenne que constructive, et pour celà quoi de
	mieux qu’internet&nbsp;? C’est ainsi qu’en parallèle de mes
	études en science
	humaines, j’ai voulu acquérir les moyens de mener à terme divers projets et me
	permettre d’ouvrir des voies d’expressions aussi bien pour moi que pour les
	autres.</p>
	<p>C'est donc selon cet objectif que j'ai débuté le développement du site 
	<a href="https://www.lesbilletsdeschrodinger.fr"><i>Les Billets de Schrödinger</i></a>. Ce site s'inscrit 
	totalement dans ma manière de voir les choses&nbsp;: j'ai des compétences et des 
	qualités, mais elles ne me seront jamais utiles sans celles des autres. Aussi 
	ais-je voulu créer un site sur l'actualité et faisant la part belle à la réflexion, 
	en souhaitant y insufler mes propres connaissances en méthodologie et éthique 
	de la recherche afin d'être le plus constructif possible.</p>
	<p>J'espère également pouvoir reprendre, dans la mesure du possible et du temps disponible, des 
	recherches dans le domaine de soiolinguistique ou de la sociologie.</p>
	
	
	<h2>Mes passions</h2>
	
	<img id="taiwan-drawing" src="../css/taiwan.png" class="left" />
	
	<p>Si j'écoute toutes sortes de musiques, je suis avant tout un fan de musique
	noire-américaine, plus précisément la Soul des années 60 et 70, ainsi que du Hip-Hop des années 90. C'est 
	probablement du au fait que ce sont des musiques très prenantes, aussi bien d'un point de vue artistique 
	que la place qu'elles ont occupé dans leur époque respective.</p>
	
	<p>Les sciences exactes sont un autre faible... Fasciné depuis tout petit par les atomes, la gravité ou 
	encore la lumière, c'est un monde de découvertes et d'étonnement sans fin. Comme beaucoup, j'attends les 
	nouvelles avancées, et en attendant je laisse à rêver de cet Univers si bien réglé, tout en me demandant 
	comment le monde peut-être aussi chaotique bien que si petit.</p>
	
	
	<p>Je suis également amoureux d’un petit pays, une petite île située à
	200km des côtes chinoises&nbsp;: Taïwan. Si la beauté de ces terres
	montagneuses adossées au Pacifique ne laissent pas indifférent, j’ai avant tout
	succombé à sa population. Société en ébullition, dynamique, faisant front face
	aux nombreux désastres naturelles avec un positivisme incurable, souvent à la
	pointe de nombreux droits pour ses citoyens, y vivre plusieurs m’aura permis de me recentrer sur moi-même et d’affirmer les
	projets que je souhaite mener dans ma propre vie. Et si les Taïwanais ne sont
	pas non plus dénués de défauts, ils m’auront toutefois appris à mieux encore
	comprendre le monde qui nous entoure.</p>
</section>