<?php $this->headTitle()->append('Curriculum Vitae'); ?>
<?php $this->headMeta()->appendName('keywords', 'curriculum vitae'); ?>


	<section id="links" class="full-width">
		<a href="https://www.linkedin.com/in/quentin-bonaventure-161a641a" class="linkedin">LinkedIn</a>
		<a href="http://www.viadeo.com/profile/0021y52ssxck4usr" class="viadeo">Viadeo</a>
<!-- 		<a href="">Breaz</a> -->
		<a href="../docs/CV_Bonaventure_Quentin.pdf" class="download-cv">Télécharger</a>
	</section>

	<section id="experiences" class="left">
		<h1>Expériences</h1>
		
		<section>
			<h1 class="date">2016 - </h1>
			<h2>Developpeur R&D - <a href="http://www.logicielnet.fr">LogicielNet</a></h2>
			<p>Responsable du développement <i>from scratch</i> d'un service web REST dédié à 
			la synchronisation de données entre diverses services, avec implémentation 
			du pattern Reactor et du PSR-7.</p>
			<p>Maintien et débuggage de la suite logiciel ORM.</p>
			<p class="tools">PHP 7.0 - PostgreSQL 9.5 - <a href="https://github.com/reactphp">ReactPHP</a> - <a href="https://github.com/goaop/framework">Go! AOP PHP 2.0</a> - Docker 1.12</p>
		</section>
		<section>
			<h1 class="date">2016 - </h1>

			<h2>Développement, édition et administration de mon site personnel - <a href="http://www.bonaventure.xyz">Bonaventure.xyz</a></h2>
			<p class="institute">Projet personnel</p>
			<p>Développement d'un site complet, frontend et backend</p>
			<p class="tools">CentOS 7 - PHP 7.0 - ZF 2.4 - PostgreSQL 9.4 - jQuery 2.2 - Apache 2.4</p>
		</section>
		<section>
			<h1 class="date">2015 - </h1>
			<h2>Développement, édition et administration d'un site sur l'actualité - <a href="http://www.lesbilletsdeschrodinger.fr">Les Billets de Schrödinger</a></h2>
			<p class="institute">Projet personnel (bientôt en ligne / accessible mais non référencé)</p>
			<p>Développement d'un site complet, frontend et backend, sur base d'un serveur</p>
			<p class="tools">CentOS 7 - PHP 5.6 - ZF 1.11 - PostgreSQL 9.3 - jQuery 1.11 - Apache 2.4</p>
		</section>
		<section>
			<h1 class="date">2014</h1>
			<h2>Participation au projet <i>Marseille en VO</i></h2>
			<p class="institute">Aix-Marseille Université / MuCEM / DGLFLF</p>
			<p>Projet visant à mettre en valeur la diversité linguistique 
			de Marseille, j'ai contribué à la mise en place du protocole 
			de l'étude de terrain avant de prendre part à celle-ci.</p>
		</section>
		<section>
			<h1 class="date">2014</h1>
			<h2>Organisation d'un colloque internationale</h2>
			<p class="institute">Aix-Marseille Université - Laboratoire IrAsia</p>
			<p>Participation à l'organisation et à la gestion de l'événement, 
			ainsi qu'à la réception des intervenants et du public.</p>
		</section>
		
		<section>
			<h1 class="date">2008 - 2010</h1>
			<h2>Développement, administration et édition d'un blog.</h2>
			<p class="institute">Projet personnel (hors ligne)</p>
			<p>Création et édition d'un blog sur Taïwan afin de partager ma 
			passion pour ce pays et débuter concrètement en développement</p>
			<p class="tools">PHP 5 - MySQL 5.2 - hébergement mutualisé</p>
		</section>
	</section>
	
	
<section id="it-skills" class="right">
	<h1>Compétences en IT</h1>
	<section id="back-end">
		<h1>Dév. back-end</h1>
		<h2>PHP 7</h2>
		<meter low="6" optimum="8" min="0" value="10" max="10"></meter>
		<h2>PostgreSQL 9</h2>
		<meter low="6" optimum="8" min="0" value="9" max="10"></meter>
		<h2>MySQL 5</h2>
		<meter low="6" optimum="8" min="0" value="7" max="10"></meter>
		<h2>Python 3</h2>
		<meter low="6" optimum="8" min="0" value="6" max="10"></meter>
		<h2>C</h2>
		<meter low="6" optimum="8" min="0" value="5" max="10"></meter>
		<h2>OCaml 4</h2>
		<meter low="6" optimum="8" min="0" value="4" max="10"></meter>
		<h2>Bash</h2>
		<meter low="6" optimum="8" min="0" value="6" max="10"></meter>
	</section>
	<section id="front-end">
		<h1>Dév. front-end</h1>
		<h2>CSS 3</h2>
		<meter low="6" optimum="8" min="0" value="10" max="10"></meter>
		<h2>HTML 5</h2>
		<meter low="6" optimum="8" min="0" value="10" max="10"></meter>
		<h2>JavaScript</h2>
		<meter low="6" optimum="8" min="0" value="7" max="10"></meter>
	</section>
	<section id="frameworks">
		<h1>Frameworks</h1>
		<h2>Zend Framework 3</h2>
		<meter low="6" optimum="8" min="0" value="10" max="9"></meter>
		<h2>Zend Expressive</h2>
		<meter low="6" optimum="8" min="0" value="7" max="10"></meter>
		<h2>jQuery</h2>
		<meter low="6" optimum="8" min="0" value="7" max="10"></meter>
		<h2>Prototype</h2>
		<meter low="6" optimum="8" min="0" value="8" max="10"></meter>
	</section>
	<section id="paradigms">
		<h1>Paradigmes</h1>
		<h2>Orienté objet</h2>
		<meter low="6" optimum="8" min="0" value="10" max="10"></meter>
		<h2>Orienté aspect</h2>
		<meter low="6" optimum="8" min="0" value="6" max="10"></meter>
		<h2>Fonctionel</h2>
		<meter low="6" optimum="8" min="0" value="5" max="10"></meter>
		<h2>Responsive / adaptive design</h2>
		<meter low="6" optimum="8" min="0" value="9" max="10"></meter>
		<h2>Structure de données</h2>
		<meter low="6" optimum="8" min="0" value="6" max="10"></meter>
		<h2>Patron de conception</h2>
		<meter low="6" optimum="8" min="0" value="7" max="10"></meter>
		<h2>MVC</h2>
		<meter low="6" optimum="8" min="0" value="8" max="10"></meter>
		<h2>Middleware</h2>
		<meter low="6" optimum="8" min="0" value="7" max="10"></meter>
		<h2>Fat Database (PgSQL)</h2>
		<meter low="6" optimum="8" min="0" value="9" max="10"></meter>
	</section>
	<section id="tools">
		<h1>Outils</h1>
		<h2>Eclipse IDE (> Neon)</h2>
		<meter low="6" optimum="8" min="0" value="8" max="10"></meter>
		<h2>Subversion (en CLI)</h2>
		<meter low="6" optimum="8" min="0" value="7" max="10"></meter>
		<h2>Git (en CLI)</h2>
		<meter low="6" optimum="8" min="0" value="7" max="10"></meter>
		<h2>Docker</h2>
		<meter low="6" optimum="8" min="0" value="4" max="10"></meter>
	</section>
	<section id="administrator">
		<h1>Administration</h1>
		<h2>Serveur CentOS 6/7</h2>
		<meter low="6" optimum="8" min="0" value="8" max="10"></meter>
		<h2>Postfix</h2>
		<meter low="6" optimum="8" min="0" value="5" max="10"></meter>
		<h2>Sécurité</h2>
		<meter low="6" optimum="8" min="0" value="4" max="10"></meter>
	</section>
</section>	

	<section id="education" class="left">
		<h1>Formation</h1>
		<section>
			<h1 class="date">2014</h1>
			<h2>Master 2 - Société chinoise / Sociolinguistique</h2>
			<p class="institute">Aix-Marseille Université</p>
			<p>Mémoire de recherche sur le débat autour des langues à Taïwan, au travers
			de la presse écrite sur internet.</p>
		</section>
		<section>
			<h1 class="date">2012</h1>
			<h2>Erasmus Mundus MULTI</h2>
			<p class="institute">National Taiwan University</p>
			<p>Boursier au sein d'une des meilleures faculté d'Asie. Validation de cours en
			<em>linguistique informatique</em>, <em>statistique</em> et <em>édition de presse</em>.</p>
		</section>
		<section>
			<h1 class="date">2011</h1>
			<h2>Licence - Langue, Littérature et Culture Chinoise</h2>
			<p class="institute">Aix-Marseille Université</p>
			<h2>DU - Didactique des Langues (FLE)</h2>
			<p class="institute">Aix-Marseille Université</p>
			<p>Suivi des cours de didactique des langues dispensés par le Laboratoire
			Paroles et Languages d'Aix-Marseille Université.
		</section>
	</section>
	
<section id="languages" class="left">
	<h1>Langues</h1>
	<section id="mastered-languages">
		<h1>Langues maîtrisées</h1>
		<h2>Français</h2>
		<meter low="6" optimum="8" min="0" value="10" max="10"></meter>
		<h2>Anglais</h2>
		<meter low="6" optimum="8" min="0" value="9" max="10"></meter>
		<h2>Mandarin</h2>
		<meter low="6" optimum="8" min="0" value="8" max="10"></meter>
	</section>
	<section id="partial-languages">
		<h1>Langues partiellement maîtrisées</h1>
		<h2>Espagnol</h2>
		<meter low="6" optimum="8" min="0" value="4" max="10"></meter>
		<h2>Taïwanais</h2>
		<meter low="6" optimum="8" min="0" value="2" max="10"></meter>
	</section>
</section>