<?php $this->headTitle()->append('Index'); ?>

<section id="slideshow">
			
	<div class="swapper-container">
		<span>Besoin d'un…</span>
		<div class="swapping-texts">
			<span>développeur web&nbsp;?</span>
			<span>administrateur serveur&nbsp;?</span>
			<span>administrateur de base de données&nbsp;?</span>
			<span>intégrateur HTML&nbsp;?</span>
		</div>
	</div><!-- 
	--><div class="slider-container">
		<div class="slider">
			<figure>
				<img src="../img/zend.png" alt="" />
				<figcaption>Au coeur de l'application, un outil de <em>qualité industriel</em> assurant sa <em>longévité</em> !</figcaption>
			</figure><!--
			--><figure>
				<img src="../img/centos.png" alt="" />
				<figcaption>Le système d'exploitation <em>libre</em>, <em>stable</em> et <em>performant</em>, déjà présent sur <em>20% des serveurs</em> !</figcaption>
			</figure><!--
			--><figure>
				<img src="../img/pgsql.png" alt="" />
				<figcaption>LA référence du <em>libre</em>, assurant l'<em>intégrité</em> et la <em>sécurité</em> de vos données !</figcaption>
			</figure><!--
			--><figure>
				<img src="../img/html-css.png" alt="" />
				<figcaption>Parce que le web mérite d'être <em>intuitif</em>, <em>attractif</em> et <em>accessible pour tous</em>.</figcaption>
			</figure>
		</div>
	</div>
</section>

<section class="left" id="services">
	<section id="frontend">
		<h1>Développement front-end</h1>
		<ul>
			<li>Intégration HTML5 / CSS3</li>
			<li>Intéractions en JavaScript (jQuery)</li>
			<li>Accessibilité et référencement</li>
		</ul>
	</section>
	<section id="backend">
		<h1>Développement back-end</h1>
		<ul>
			<li>Conception et mise en place</li>
			<li>Architecture MVC</li>
			<li>Framework Zend</li>
			<li>Base de données en couche épaisse</li>
			<li>Mise en place et gestion de serveur</li>
		</ul>
	</section>
	<section id="server">
		<h1>Administration serveur</h1>
		<ul>
			<li>Mise en place et hébergement du serveur</li>
			<li>Sécurisation par SSL</li>
			<li>Boîtes mail</li>
		</ul>
	</section>
</section>

<section class="right">
	<h1>&laquo;&nbsp;Full-stack&nbsp;&raquo;</h1>
	<p>Celà signifie tout simplement que mon domaine d'expertise s'étant sur l'ensemble des couches constituantes 
	d'un site web&nbsp;: ce qui est présenté à l'écran, la programmation et le traitement qui se trouve dérrière,
	la base de donnée, et enfin le serveur sur lequel tout repose.</p>
</section>
	


<section class="right" id="social-networks">
	<h1>Retrouvez-moi sur&hellip;</h1>
	<div class="flex-box">
    	<a href="https://www.linkedin.com/in/quentin-bonaventure-161a641a" id="linkedin">LinkedIn</a>
    	<a href="http://www.viadeo.com/profile/0021y52ssxck4usr" id="viadeo">Viadeo</a>
    	<a href="http://stackoverflow.com/users/4593653/quentin-bonaventure?tab=profile" id="stackoverflow">Stack Overflow</a>
    	<a href="https://github.com/QBonaventure" id="github">GitHub</a>
    </div>
</section>

<!-- <section class="left"> -->
<!-- 	<h1>Sciences informatiques</h1> -->
<!-- 	<p>Découvert alors que je souhaitais me donner les moyens de contrôler mes propres moyens  -->
<!-- 	d'expressions sur internet, ma curiosité pour le développement informatique n'a cessé d'être de  -->
<!-- 	plus en plus dévorante. Commancant par le plus basique - PHP procédural, MySQL et CSS -, il m'aura  -->
<!-- 	vite fallu mieux comprendre comment tout cela fonctionne, comment mieux effectuer mes choix ou  -->
<!-- 	comment tout simplement "mieux développer".</p> -->
<!-- 	<p>Développeur <em>accompli</em>, <em>autonome</em> et <em>rigoureux</em>, j'ai aussi acquis une <em>polyvalence</em>  -->
<!-- 	dans de multiple  -->
<!-- 	domaine bien que je maintienne une spécialisation dans le développement web. Alors que ma propre  -->
<!-- 	vie prend un tournant, une évidence s'impose : ma passion doit être mise au service des autres.</p>  -->
	
	
	
<!-- </section> -->


<!-- <section class="right"> -->
<!-- 	<h1>Sciences humaines</h1> -->
<!-- 	<p>Intrigué depuis très longtemps par les sciences humaines, que ce soit la géopolitique, la  -->
<!-- 	sociologie ou la linguistique, j'ai accompli un parcours universitaire en ce sens. Que soit pour les -->
<!-- 	<em>langues chinoises</em>, dont l'apprentissage était un véritable défi, la <em>didactique des -->
<!-- 	langues</em>, qui m'ont autant apporté d'un point de vue personnel qu'académique, à la -->
<!-- 	<em>sociolinguistique</em>, discipline transversale offrant une nouvelle vision de la société,  -->
<!-- 	j'ai su mettre ma passion au service de la rigueur académique</p> -->
<!-- 	<p>Toutefois, malgré un parcours académique aussi réussi qu'épanouissant, il est temps de laisser  -->
<!-- 	de me laisser être plus encore en phase avec mon temps.</p>  -->
<!-- </section> -->